### ISSUE TITLE
SwiftAddressBookPerson.compositeName

### ISSUE THREAD

**Issue by edekhayser** [SocialbitGmbH/SwiftAddressBook#11]
There is currently a way to get the composite name *format* but not a quick property to get the contact's composite name itself. I believe there is a method for ABAddressBook that gets the composite name, and it wouldn't seem to difficult to add this feature.

**Comment by TAKeanice** [comment]
You are right, that is one of the ugly things in ABAddressBook: compositeName is not actually a person property, but a derived property of sources or persons. I´m quite busy at the moment, but if you´d like to contribute by implementing it similar to the other person properties, and make a pull request, that would be really helpful https://developer.apple.com/library/ios/documentation/AddressBook/Reference/ABRecordRef_iPhoneOS/index.html#//apple_ref/c/func/ABRecordCopyCompositeName
