### ISSUE TITLE
How to add person to specific named group

### ISSUE THREAD

**Issue by elprl** [SocialbitGmbH/SwiftAddressBook#15]
Can this library add a custom group with a specific name? I see the group.create() method but I don't see a place to enter a name. How does one then add a new person to that newly formed group?

**Comment by TAKeanice** [comment]
Setting the name property should do the trick

**Comment by TAKeanice** [comment]
Ok, I recognized that I have only implemented the getter ;) Will push the setter soon

**Comment by TAKeanice** [comment]
Corrected my mistake in the new version (also Cocoapod version!) 0.2.1
