### ISSUE TITLE
Crash when setting phoneNumber property

### ISSUE THREAD

**Issue by albertbori** [SocialbitGmbH/SwiftAddressBook#16]
Code:
```
var person = SwiftAddressBookPerson.create()
var phone = MultivalueEntry(value: "(480) 555-3176", label: "mobile", id: 0)
person.phoneNumbers = [phone]
```

Stack trace:
```
#0	0x000000011a10f5f6 in specialization <ObjectiveC.NSString with ObjectiveC.NSString : Swift.AnyObject> of SwiftAddressBook.SwiftAddressBookPerson.(setMultivalueProperty in _ECEF355CFD253D8039C191CB27BDAECD) (SwiftAddressBook.SwiftAddressBookPerson)<A : Swift.AnyObject>(Swift.Int32, Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<A>>>) -> () at /Users/me/dev/myapp-ios/Pods/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:705
#1	0x000000011a0f6210 in specialization <Swift.String, ObjectiveC.NSString with ObjectiveC.NSString : Swift.AnyObject> of SwiftAddressBook.SwiftAddressBookPerson.(convertMultivalueEntries in _ECEF355CFD253D8039C191CB27BDAECD) (SwiftAddressBook.SwiftAddressBookPerson)<A, B : Swift.AnyObject>(Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<A>>>, converter : (A) -> B) -> Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<B>>> [inlined] at /Users/me/dev/myapp-ios/Pods/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:700
#2	0x000000011a0f6193 in SwiftAddressBook.SwiftAddressBookPerson.phoneNumbers.setter : Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<Swift.String>>> at /Users/me/dev/myapp-ios/Pods/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:595
#3	0x0000000119f9e323 in AutomationTests.MyTests.(setUpAddressBook in _BC85590BB5A8F9533CC2C3C828C81FE1) (AutomationTests.MyTests.Type)() -> () at /Users/me/dev/myapp-ios/myapp/AutomationTests/MyTests.swift:168
#4	0x0000000119f98168 in AutomationTests.MyTests.addAddressBookRecipient (AutomationTests.MyTests.Type)(Swift.String) -> () [inlined] at /Users/me/dev/myapp-ios/myapp/AutomationTests/MyTests.swift:117
#5	0x0000000119f98163 in AutomationTests.MyTests.testAskToLocalAndRemoteRecipients (AutomationTests.MyTests)() -> () at /Users/me/dev/myapp-ios/myapp/AutomationTests/MyTests.swift:25
#6	0x000000010bae3c8c in __invoking___ ()
#7	0x000000010bae3ae2 in -[NSInvocation invoke] ()
#8	0x000000011a06e0f7 in -[XCTestCase invokeTest] ()
#9	0x000000011a06e2f8 in -[XCTestCase performTest:] ()
#10	0x000000011a077bf5 in -[XCTest run] ()
#11	0x000000011a06cffb in -[XCTestSuite performTest:] ()
#12	0x000000011a077bf5 in -[XCTest run] ()
#13	0x000000011a06cffb in -[XCTestSuite performTest:] ()
#14	0x000000011a077bf5 in -[XCTest run] ()
#15	0x000000011a06cffb in -[XCTestSuite performTest:] ()
#16	0x000000011a077bf5 in -[XCTest run] ()
#17	0x000000011a06a0bc in __25-[XCTestDriver _runSuite]_block_invoke ()
#18	0x000000011a074ead in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
#19	0x000000011a069ff0 in -[XCTestDriver _runSuite] ()
#20	0x000000011a06aa1d in -[XCTestDriver _checkForTestManager] ()
#21	0x000000011a07aaf0 in +[XCTestProbe runTests:] ()
#22	0x000000010b43dd55 in __NSFireDelayedPerform ()
#23	0x000000010bb53f64 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
#24	0x000000010bb53b25 in __CFRunLoopDoTimer ()
#25	0x000000010bb16e5d in __CFRunLoopRun ()
#26	0x000000010bb16486 in CFRunLoopRunSpecific ()
#27	0x000000010e9169f0 in GSEventRunModal ()
#28	0x000000010c21b420 in UIApplicationMain ()
#29	0x000000010ad3d10e in top_level_code at /Users/me/dev/myapp-ios/myapp/AppDelegate.swift:20
#30	0x000000010ad3d14a in main ()
#31	0x00000001122f8145 in start ()
```

**Comment by TAKeanice** [comment]
Is there anything special about your setup? Do you have access rights to the address book? Are you using the main branch?

**Comment by albertbori** [comment]
I'm using the main branch. Nothing special about my setup. Running Xcode 6.1 (6A2008a).

To help identify issues and improve stability, I've created a unit test target in the example project here: https://github.com/SocialbitGmbH/SwiftAddressBook/pull/17

The error I'm having is showcased in those tests, among other issues that the tests have brought to light.

**Comment by TAKeanice** [comment]
Ok, what about the access rights? I have not seen any place where you ask for permission to access the address book in the tests. I´d recommend to wrap any sequence you use for testing into

```Swift
swiftAddressBook?.requestAccessWithCompletion({ (success, error) -> Void in
    if success {
        //do something with swiftAddressBook
    }
    else {
        //no success, access denied. Optionally evaluate error
    }
})
```

and perform all asserts inside the `if success` part. Otherwise they could possibly fail, even without bugs.

**Comment by elprl** [comment]
albertbori, I used to get crashes on the setMultivalueProperty method, but it has changed recently, have you got latest?

**Comment by albertbori** [comment]
@TAKeanice I'm added my code to that block. I have granted access permissions to the address book. I still get the crash. I get the same crash when running the unit tests in #17. Try running those tests and see if it crashes for you.

@elprl I get the error while running the very latest commit in the master branch. (Using cocoapods)

**Comment by TAKeanice** [comment]
Ok, I will test until Sunday at most

**Comment by TAKeanice** [comment]
I must say, I´m a little clueless on this. The errors I get are not consistent, they appear at different places all over the test (in the testAddGetPerson function). Still, I found a little mistake in my code, but that does not appear to solve the problem. See d9ed3ed943e173d4fc9532334f10c063bd5d8fec on that mistake.

**Comment by TAKeanice** [comment]
Is it possible, that the tests are run asynchronously? Sometimes I get two threads, both executing swiftAddressBook?.save() at the same time. The crash finally happens inside ABAddressBook as it appears to me...

**Comment by albertbori** [comment]
To get two tests that run asynchronously, you'd have to create a single test that spins off 2+ threads that call the swiftAddressBook?.save().

**Comment by TAKeanice** [comment]
strange. Very strange. I switched off optimization on the pod (that to make sure it´s no fault of the compiler) and I´m getting consistently the same error now, some bad access originating from the first `swiftAddressBook?.save()` in testAddRemovePerson and the first `swiftAddressBook.save()` in the TestAddEditRemovePerson

**Comment by TAKeanice** [comment]
Ok. Now that I´ve set expectations and wait calls on each test, it seems to work (the tests fail in many cases, but they don´t throw errors any more)

**Comment by TAKeanice** [comment]
requestAccessWithCompletion is an asynchronous call. So we´ll need the expectations on the unit tests anyway

**Comment by TAKeanice** [comment]
Finally got consistent results, by increasing wait times on the test, switching off optimization on both projects and improving the tests in some places. See new pull request @albertbori  :)

**Comment by TAKeanice** [comment]
@albertbori still having those issues after my pull request for your tests?

**Comment by albertbori** [comment]
After merging, I get the following crash when running those tests:

```
#0	0x00000001039165d1 in SwiftAddressBook.errorIfNoSuccess ((Swift.UnsafeMutablePointer<Swift.Optional<Swift.Unmanaged<ObjectiveC.CFError>>>) -> Swift.Bool) -> Swift.Optional<ObjectiveC.CFError> [inlined] at /Users/me/dev/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:1024
#1	0x00000001039165d1 in specialization <ObjectiveC.NSString with ObjectiveC.NSString : Swift.AnyObject> of SwiftAddressBook.SwiftAddressBookPerson.(setMultivalueProperty in _ECEF355CFD253D8039C191CB27BDAECD) (SwiftAddressBook.SwiftAddressBookPerson)<A : Swift.AnyObject>(Swift.Int32, Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<A>>>) -> () at /Users/me/dev/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:707
#2	0x00000001038fb380 in specialization <Swift.String, ObjectiveC.NSString with ObjectiveC.NSString : Swift.AnyObject> of SwiftAddressBook.SwiftAddressBookPerson.(convertMultivalueEntries in _ECEF355CFD253D8039C191CB27BDAECD) (SwiftAddressBook.SwiftAddressBookPerson)<A, B : Swift.AnyObject>(Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<A>>>, converter : (A) -> B) -> Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<B>>> [inlined] at /Users/me/dev/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:700
#3	0x00000001038fb303 in SwiftAddressBook.SwiftAddressBookPerson.emails.setter : Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<Swift.String>>> at /Users/me/dev/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:523
#4	0x00000001125d05f2 in SwiftAddressBookTests.SwiftAddressBookTests.(testAddRemovePerson (SwiftAddressBookTests.SwiftAddressBookTests) -> () -> ()).(closure #1) at /Users/me/dev/SwiftAddressBook/Example/SwiftAddressBookTests/SwiftAddressBookTests.swift:140
#5	0x0000000105cf04ef in __37-[ABTCC accessRequestWithCompletion:]_block_invoke ()
#6	0x00000001070c3af6 in _dispatch_call_block_and_release ()
#7	0x00000001070ddaf4 in _dispatch_client_callout ()
#8	0x00000001070ca464 in _dispatch_root_queue_drain ()
#9	0x00000001070cb2c9 in _dispatch_worker_thread3 ()
#10	0x000000010745d637 in _pthread_wqthread ()
#11	0x000000010745b40d in start_wqthread ()
```

**Comment by TAKeanice** [comment]
Also when you disable compiler optimization? That's how I got rid of that.

**Comment by albertbori** [comment]
When I have swift compiler optimization set to `None [-Onone]`, I still get the error.

![screen shot 2015-02-27 at 8 17 56 pm](https://cloud.githubusercontent.com/assets/1742709/6424622/c8a72a9e-bebd-11e4-855e-91f6a0426427.png)

Is that the optimization setting you were talking about?

**Comment by TAKeanice** [comment]
Yes, on both, pods target and sample project target. But I've tested with optimizations switched on again, and I'm not getting exceptions any more either with or without optimization.
I'm using the head of this repo since I've merged your pull request, where I fixed some more stuff already. Is that where you are testing, too? 
Very sorry this bug takes so long, and is so persistent. Can you try increasing the wait times on the tests even more, to some ridiculous amount such as 100 seconds, to definitely rule out that the problem is down to the asynchronous nature of the request access call?

**Comment by albertbori** [comment]
I pulled the latest version, and was able to run the tests without any crashes. (Some of the tests are failing, but that's a separate issue)

**Comment by TAKeanice** [comment]
Phew, glad this issue has finally come to an end! Thanks for your patience! I have no idea about the find people feature, it's working on self-created contacts only. For the address feature, I've opened another issue.
