### ISSUE TITLE
Crash when accessing a nil property

### ISSUE THREAD

**Issue by shannoga** [SocialbitGmbH/SwiftAddressBook#2]
Hi
Thanks for the great code, I am converting an app to swift, so I am pretty new to it.

I found that when I access a person property that is not set to it, I get a crash on this method.

```swift
   private func extractProperty<T>(propertyName : ABPropertyID) -> T? {
        return ABRecordCopyValue(self.internalRecord, propertyName).takeRetainedValue() as? T
    }
```
Checking this I found that if ABRecordCopyValue returns nil, it immediately crashes.

I will try to find a fix and inform you if I will.

Thanks
Shani

**Comment by elprl** [comment]
I'm finding the fix will on occasion still crash even when I use the code:
    return ABRecordCopyValue(self.internalRecord, propertyName)?.takeRetainedValue() as? T

I specifically get it when trying to access phone numbers.

**Comment by TAKeanice** [comment]
Thank you, I will test this during this week. Does the crash happen with your proposed fix as well? Or only with the fix I suggested?

**Comment by elprl** [comment]
This is a strange one for sure. I have the following code called from a tableview cellforRow method:
```
func configureCell(cell: MPPContactTableCell, forContact contact: SwiftAddressBookPerson?) {
        
        if let client = contact {
            if let firstNom = client.firstName as String? {
                cell.firstNameLbl.text = firstNom + " "
            }
            
            if let secNom = client.lastName as String? {
                cell.lastNameLbl.text = secNom
            }
            
            if let email = client.emails?.first {
                cell.infoLbl.text = email.value
            } else if let number = client.phoneNumbers?.first { // crashes here EXC_BAD_ACCESS (code=1, address=0x0)
                cell.infoLbl.text = number.value
            }
        }
    }
```

Following that up the stack, it crashes on Thread 1 in the method:
```
private func extractProperty<T>(propertyName : ABPropertyID) -> T? {
        return ABRecordCopyValue(self.internalRecord, propertyName)?.takeRetainedValue() as? T
    }
```

**Comment by elprl** [comment]
So its a memory issue (trying to access an object that has been released). I suspect it could be down to the way I'm storing the initial array of contacts. That said, it doesn't explain why emails work fine but phone numbers don't.

If I simplify the code to 
```
func testloadContacts() {
        if let defaultSource = mySwiftAddressBook?.defaultSource {
            
            if let people = mySwiftAddressBook?.allPeopleInSourceWithSortOrdering(defaultSource, ordering: SwiftAddressBookOrdering.firstName) {
                for person in people {
                    let firstName = person.firstName?
                    let lastName = person.lastName?
                    let email = person.emails?.map({ $0.value }).first
                    let phone = person.phoneNumbers?.map({ $0.value }).first
                    println("firstName: \(firstName)\nlastName: \(lastName)\nemail: \(email)\nphone: \(phone)")
                }
            }
        }
    }
```

This runs fine without crash. I'll investigate more by stripping out more code and testing.

**Comment by TAKeanice** [comment]
Thank you very much. I have tested a little myself now, and seem not to be able to reproduce your issue:
 ```swift
swiftAddressBook?.requestAccessWithCompletion { (b :Bool, _ :CFError?) -> Void in
            if b {
                let people = swiftAddressBook?.allPeople?
                
                let numbers = people?.map { (p) -> (Array<String?>?) in
                    return p.phoneNumbers?.map { return $0.value }
                }
                let emails = people?.map { (p) -> (Array<String?>?) in
                    return p.emails?.map { return $0.value }
                }
                
                println("\(numbers)\n\n\(emails)")
            }
        }
```

does succeed with the following output (on the simulator):

```
Optional([Optional([Optional("123456"), Optional("123456")]), Optional([Optional("123456"), Optional("123456")]), nil, Optional([Optional("123456"), Optional("123456")]), Optional([Optional("123456"), Optional("123456")]), Optional([Optional("123456"), Optional("123456")])])

Optional([Optional([Optional("kate-bell@mac.com"), Optional("www.icloud.com")]), Optional([Optional("d-higgins@mac.com")]), Optional([Optional("John-Appleseed@mac.com")]), Optional([Optional("anna-haro@mac.com")]), Optional([Optional("hank-zakroff@mac.com")]), nil])
```

**Comment by TAKeanice** [comment]
Additionally, unrelated to this, I think the casts `as String?` should not be necessary. `String?` should be inferred as type automatically

**Comment by elprl** [comment]
I think the crash was down to accessing a stored array of the synced contacts through a closure, causing my memory problems. Still unsure why just phone numbers highlighted the problem though. Once I changed my calls to be more thread friendly I'm not seeing the crash. I think it's safe to close this bug.
