### ISSUE TITLE
ABMultiValueCopyLabelAtIndex may return NULL

### ISSUE THREAD

**Issue by marbetschar** [SocialbitGmbH/SwiftAddressBook#20]
I've run into some issues where the extractMultivalueProperty forced a Crash of the App.
The reason was, because the ABMultiValueCopyLabelAtIndex may return nil and therefore the label is not set. So I changed the function like the following:

    private func extractMultivalueProperty<T>(propertyName : ABPropertyID) -> Array<MultivalueEntry<T>>? {
        var array = Array<MultivalueEntry<T>>()
		if let multivalue: ABMultiValue = extractProperty(propertyName) as ABMultiValue?{
			for i : Int in 0..<(ABMultiValueGetCount(multivalue)) {
				if let v = ABMultiValueCopyValueAtIndex(multivalue, i).takeRetainedValue() as? T{
					let id: Int = Int(ABMultiValueGetIdentifierAtIndex(multivalue, i))
					var label = ""
					if let pointerToLabel = ABMultiValueCopyLabelAtIndex(multivalue, i){
						label = pointerToLabel.takeRetainedValue()
					}
					
					array.append(MultivalueEntry(value: v, label: label, id: id))
				}
			}
		}

        if array.count > 0 {
            return array
        } else {
            return nil
        }
    }

**Comment by TAKeanice** [comment]
I think a better solution would be changing the type of the label to String?
