### ISSUE TITLE
How to sync "street2"?

### ISSUE THREAD

**Issue by marbetschar** [SocialbitGmbH/SwiftAddressBook#22]
I'm trying to sync the whole postal address with the iOS address book.
Unfortunately I can't see a way to sync the second street field?
Since the only fields defined in SwiftAddressBookAddressProperty are: street, city, state, zip, country, countryCode.

![address](https://cloud.githubusercontent.com/assets/392542/6547645/c896b566-c5dd-11e4-832c-4ec9705ebdc6.png)

So how can I achieve a full address sync?

**Comment by TAKeanice** [comment]
There is definitely only one street entry predefined in the address dictionary. Have you tried using a line break?

**Comment by marbetschar** [comment]
Cool! The line break did the trick!
