### ISSUE TITLE
How can I refresh my swiftAddressBook instance?

### ISSUE THREAD

**Issue by nawok** [SocialbitGmbH/SwiftAddressBook#23]
When I launch my app and then switch to the standard iOS Address Book and change a contact, I cannot get the new field values for that contact unless I relaunch my app. Here is my class:

```Swift
class Client: NSManagedObject {
    @NSManaged var addressBookID: NSNumber
    @NSManaged var name: NSString?
    @NSManaged var birthday: NSDate?

    func fetchInfo() {
        if let person = swiftAddressBook?.personWithRecordId(self.addressBookID.intValue) {
            self.name = person.compositeName
            self.birthday = person.birthday
        }
    }
}
```

How can I modify my fetchInfo() function to get the refreshed contact data?
I really appreciate any help you can provide.

**Comment by TAKeanice** [comment]
There is a reset method which should sync your local copy with the global one, removing your unsaved changes. You could do that in the app delegate

**Comment by nawok** [comment]
Thanks! It worked!
```Swift
// AppDelegate.swift
func applicationWillEnterForeground(application: UIApplication) {
    swiftAddressBook?.revert()
}
```

**Comment by TAKeanice** [comment]
@nawok please close if this is a solution for you :)
