### ISSUE TITLE
Check ABRecord for type?

### ISSUE THREAD

**Issue by marbetschar** [SocialbitGmbH/SwiftAddressBook#24]
I'm trying to distinct between people and organization during a sync process.
Now I'm stuck with detecting whether it's an organization or a person I'm trying to sync.

Here's the code which throws a "unexpected nil" exception:

    if let companies = swiftAddressBook?.allPeopleInSource(defaultSource){
        for company in companies{
            if company.type == .organization{ // <= error is thrown here

Which seems to be thrown in SwiftAddressBook over here:

    public enum SwiftAddressBookPersonType {
    
    case person, organization
    
    init(type : CFNumber?) {
        //error is thrown on next line because "type" is nil
        if CFNumberCompare(type, kABPersonKindPerson, nil) == CFComparisonResult.CompareEqualTo

**Comment by marbetschar** [comment]
Any Idea why the error is thrown? Unfortunately I need to resolve this issue asap because I have to finish the App till the end of this week :(

Any help is highly appreciated.

**Comment by marbetschar** [comment]
Ok I think I tracked down the error: It only occurs during syncing a person with a "MiddleName".
That pointed me into the right direction - as I stumbled across the following piece of code which is responsible of setting/getting the SwiftAddressBookPersonType:

    public var type : SwiftAddressBookPersonType? {
        get {
            return SwiftAddressBookPersonType(type : extractProperty(kABPersonMiddleNameProperty))
        }
        set {
            setSingleValueProperty(kABPersonMiddleNameProperty, newValue?.abPersonType)
        }
    }

Seems like a property mismatch here. I assume the `kABPersonMiddleNameProperty` should be named `kABPersonKindProperty` ?

However, after inserting the kABPersonKindProperty instead of `kABPersonMiddleNameProperty` the sync seems to run fine.

**Comment by TAKeanice** [comment]
Sorry for not answering yet. The reason is simple: `CFNumberCompare(number1, number2, nil)` throws an exception if either `number1` or `number2` or both are `nil` - thus, if no type is set on a user, initializing the `SwiftAddressBookPersonType` struct from type nil will crash.

**Comment by TAKeanice** [comment]
At least I hope that was your issue. Otherwise you can of course reopen that one!

**Comment by TAKeanice** [comment]
Sorry, I have read your comments too late. I´ve fixed one bug, however, that bug was not the only one  responsible for the issue.
