### ISSUE TITLE
Accessing source.sourceName crashes the app

### ISSUE THREAD

**Issue by marbetschar** [SocialbitGmbH/SwiftAddressBook#25]
Hi!
I'm trying to access the name of a address book source in the simulator.
Unfortunately every time I'm accessing it, the simulator crashes.

Responsible for the crash is a unwrapped optional with the value "nil" in the sourceName getter method:

     public var sourceName : String? {
        get {
            let value: AnyObject? = ABRecordCopyValue(internalRecord, kABSourceNameProperty)?.takeRetainedValue()
            if value != nil {
                return value as CFString //this line throws the unwrapped optional exception
            }
            else {
                return nil
            }
        }
    }

Any idea what's going wrong here?

I'm accessing the getter as follows:

    if defaultSource.sourceName != nil{

**Comment by marbetschar** [comment]
Interestingly it seems to work if I change the getter method like the following:

    public var sourceName : AnyObject? {
        get {
			return ABRecordCopyValue(internalRecord, kABSourceNameProperty)?.takeRetainedValue()
        }
    }

But I don't think this is the way it is supposed to work :(
Any other ideas?

**Comment by marbetschar** [comment]
Cool! How may I upgrade to the new release using Cocoapods?

**Comment by TAKeanice** [comment]
I have not made a cocoapods release yet. Just removing the version number should get you the newest version on github!

**Comment by marbetschar** [comment]
Thank you very much!!
Seems to be fixed.

After updating I ran just into another issue - seems like I no longer able to check a SwiftAddressBookPerson for nil:

    if ABPerson != nil { // -> xCode complains: "Type 'SwiftAddressBookPerson' does not conform to protocol 'Equatable'
    }

Do these issues have anything in common...?

**Comment by TAKeanice** [comment]
I can´t see the type of the `ABPerson` here. But it says `SwiftAddressBookPerson` instead of `SwiftAddressBookPerson?`, which means it´s already unwrapped. SwiftAddressBookPerson does indeed not conform to the `Equatable` protocol, but optionals do.
