### ISSUE TITLE
install copying AddressBookWrapper.swift is not sufficient

### ISSUE THREAD

**Issue by kbrown** [SocialbitGmbH/SwiftAddressBook#28]
Docs say I can just copy AddressBookWrapper.swift, but there are other files required.  e.g,. AddressBookRecord.  Docs should be fixed.

**Comment by kbrown** [comment]
Also I needed to import UIKit in SwiftAddressBookPerson.swift.  ( Will try cocoapods when I give up on iOS7 )

**Comment by kbrown** [comment]
Need to try Cocoapods...

**Comment by TAKeanice** [comment]
Yes, you're right, I didn't fix the docs after  splitting the files. UIKit  should not be necessary. which line was the problem?

**Comment by TAKeanice** [comment]
You should only use cocoapods if you don't need your app to be compatible with iOS 7.  With the final version of cocoapods 36.0, you need to add an additional flag to allow frameworks in order to use swift address book. I have to fix the doc there, too

**Comment by TAKeanice** [comment]
fixed readme in 10a85f6c35e11f7ede81ce6d1bb68ad0f6bf9860

**Comment by TAKeanice** [comment]
Btw. @kbrown , if it is your comment on reddit, could you please review it? So that others keep finding this little helper ;) .
