### ISSUE TITLE
Testing if there is no email attached to contact?

### ISSUE THREAD

**Issue by gabriel-jones** [SocialbitGmbH/SwiftAddressBook#30]
I want to test to see if a person has an email listed in the contacts. But when I try to do something like this: 

```                        
 if let test = people[i].emails?.map({($0.value as String)})[0]  {

                   
```
It doesn't work. Instead, the program crashes. Any ideas how to get around this?

**Comment by TAKeanice** [comment]
Of course you can´t access an index in an empty array. Look for `.count == 0` or something like that

**Comment by gabriel-jones** [comment]
Thanks, got it working.
