### ISSUE TITLE
SwiftAddressBook Broken in Xcode 6.3

### ISSUE THREAD

**Issue by marbetschar** [SocialbitGmbH/SwiftAddressBook#32]
Seems like SwiftAddressBook is Broken in Xcode 6.3 due to "The implicit conversions from bridged Objective-C classes (NSString/NSArray/NSDictionary) to their corresponding Swift value types (String/Array/Dictionary) have been removed, making the Swift type system simpler and more predictable.
...
In order to perform such a bridging conversion, make the conversion explicit with the as keyword."

See Xcode Release Notes:
https://developer.apple.com/library/ios/releasenotes/DeveloperTools/RN-Xcode/Chapters/xc6_release_notes.html#//apple_ref/doc/uid/TP40001051-CH4-DontLinkElementID_23

**Comment by TAKeanice** [comment]
Please check out the swift 1.2 take 2 branch

**Comment by TAKeanice** [comment]
See https://github.com/SocialbitGmbH/SwiftAddressBook/issues/7 and https://github.com/SocialbitGmbH/SwiftAddressBook/pull/31
