### ISSUE TITLE
Add final support for Swift 1.2

### ISSUE THREAD

**Issue by albertbori** [SocialbitGmbH/SwiftAddressBook#33]
Swift 1.2 is officially released now. It should be merged into the main branch. (Mind the unit tests)

**Comment by TAKeanice** [comment]
I am waiting for travis ci to solve the unit testing problem first, please have a look at https://github.com/SocialbitGmbH/SwiftAddressBook/pull/31

**Comment by TAKeanice** [comment]
Travis was fixed! See the [Travis Blog](http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability)
