### ISSUE TITLE
How to sort retrieved contact by name?

### ISSUE THREAD

**Issue by brucelee206** [SocialbitGmbH/SwiftAddressBook#34]
Are there any ways to sort swiftAddressBook?.allPeople by name of contact?

**Comment by TAKeanice** [comment]
Use the standard sort functions for arrays in Swift. There is also the function all people with sort ordering

**Comment by aTylerRice** [comment]
tried using function allPeopleInSourceWithSortOrdering but I don't know how to pass in the SwiftAddressBookSource  I just need the regular standard source for the phonebook.. How do I create that kind of source?

**Comment by TAKeanice** [comment]
SwiftAddressBookWrapper has the variable "default source", which is the "standard source for phonebook".
