### ISSUE TITLE
Loading Contacts More than Twice Results in Fatal Error

### ISSUE THREAD

**Issue by Archivus** [SocialbitGmbH/SwiftAddressBook#35]
Hey, this a great and helpful tool! There's just one little problem with it; if you load the contacts more than once the app will crash with the following error: 'fatal error: Array index out of range'

**Comment by TAKeanice** [comment]
What method do you use? Would you mind adding that test case to the unit tests?

**Comment by Archivus** [comment]
I imported the files into my own project. Also, what do you mean by the last bit?

**Comment by TAKeanice** [comment]
I mean the function that you are using to load the contacts. And please try to google unit tests before asking.
