### ISSUE TITLE
Multiple licenses

### ISSUE THREAD

**Issue by arctouch-ericchamberlain** [SocialbitGmbH/SwiftAddressBook#38]
The license file lists an Apache license, but SwiftAddressBookWrapper.swift has a GPLv3 license, which is not compatible with the App Store.

What is the correct licensing for the project?

**Comment by TAKeanice** [comment]
Apache. We recently changed it to avoid that exact problem. Sorry for not correcting it in the file.
If you want to use it, that´s ok. Although, if you want to contribute, you should sign the contributors agreement. For more information see the readme
