### ISSUE TITLE
Missing import in SwiftAddressBookPerson

### ISSUE THREAD

**Issue by funky-monkey** [SocialbitGmbH/SwiftAddressBook#39]
Please import UIKit instead of Foundation.

**Comment by TAKeanice** [comment]
Actually, SwiftAddressBook should not need UIKit. There is no interaction with any UI... Api whatsoever. Please show me the place where the code breaks due to not importing UIKit

**Comment by funky-monkey** [comment]
In the class SwiftAddressBookPerson.swift; Since you are setting and getting UIImages from the AB, it does need UIKit. Plus including UIKit also includes Foundation :-)

**Comment by TAKeanice** [comment]
You´re right :) I´ll fix it soon.
