### ISSUE TITLE
New branch for Swift 1.2

### ISSUE THREAD

**Issue by elprl** [SocialbitGmbH/SwiftAddressBook#4]
I recommend adding a new branch for Swift 1.2 thats in Xcode 6.3 Beta. At the moment, I'm seeing segmentation faults due to this library even after using the conversion tool. 

Compiler errors on your NSString extension.

**Comment by elprl** [comment]
So Swift 1.2 doesn't like the singleton code. I can remove the segmentation faults and Lipo errors by commenting out this code:

```swift
//MARK: global address book variable

var mySwiftAddressBook : SwiftAddressBook? {
get {
    if let instance = swiftAddressBookInstance {
        return instance
    }
    else {
        swiftAddressBookInstance = SwiftAddressBook(0)
        return swiftAddressBookInstance
    }
}
}


//MARK: private address book store

private var swiftAddressBookInstance : SwiftAddressBook?
```

**Comment by cwoloszynski** [comment]
Can you please post your fixes.  I am looking at the segmentation fault also and I see that commenting out the NSString extension fixes the segmentation fault but leave the code with compiler errors.   I am using Xcode 6.1.1 (Swift 1.1) and I want to use a library like this.

**Comment by elprl** [comment]
This issue is for Swift 1.2 only which has some major changes to the language. You would have to go through the conversion process which alters many of the 'as' statements. I then commented out the NSString extension and made the recommended changes by the compiler that resulted from it. I then added a different type of singleton to the class and commented out all of the above code.

```swift
class SwiftAddressBook {
    
    var internalAddressBook : ABAddressBook!
    
    class var sharedInstance: SwiftAddressBook {
        struct Static {
            static var instance: SwiftAddressBook?
            static var token: dispatch_once_t = 0
        }
        
        dispatch_once(&Static.token) {
            Static.instance = SwiftAddressBook(0)
        }
        
        return Static.instance!
    }
```

**Comment by cwoloszynski** [comment]
Thanks.  I ended up with the following.  BTW, I have read that this approach is clean for dispatch_once items like a singleton and reads very cleanly.


private let _sharedInstance = SwiftAddressBook(0)

//MARK: Address Book

class SwiftAddressBook {
    
    var internalAddressBook : ABAddressBook!
    
    private init?(_ dummy : Int) {
        var err : Unmanaged<CFError>? = nil
        let ab = ABAddressBookCreateWithOptions(nil, &err)
        if err == nil {
            internalAddressBook = ab.takeRetainedValue()
        }
        else {
            return nil
        }
    }
    
    class func sharedInstance() -> SwiftAddressBook? {
        return _sharedInstance
    }

**Comment by TAKeanice** [comment]
I will branch for Swift 1.2, and would appreciate if you create pull requests for the fixes needed!

**Comment by TAKeanice** [comment]
Some changes towards a Swift 1.2 version are committed
