### ISSUE TITLE
Gives me an error

### ISSUE THREAD

**Issue by hitec** [SocialbitGmbH/SwiftAddressBook#40]
As far as I can tell, the pod is installed correctly. I am facing an issue when ever I try to import "SwiftAddressBook"  it tells me No such module exist

**Comment by TAKeanice** [comment]
Have you tested the sample application? There, it is done exactly this way.

**Comment by joubin** [comment]
I am having the same issue. I made a video. Maybe that'll help you see what Im seeing.

https://www.youtube.com/watch?v=1WZQvo5-KHA

**Comment by TAKeanice** [comment]
Sorry, seems like I have not maintained the pod properly. The version the pod was on was still no Swift 1.2... Now, a new pod version was pushed. Please test again with this. I will close this issue, since I could reproduce it now and it was solved for me through my last test.

**Comment by TAKeanice** [comment]
Use `pod update` to get version 0.4.3

**Comment by TAKeanice** [comment]
I ran into the same issue again today. Solved by moving to a folder without special symbols.

**Comment by danielkiedrowski** [comment]
Running in this error again. Using 0.6.2, Cocoapods 1.0.1, XCode 7.3.1
