### ISSUE TITLE
Add contact from vcard

### ISSUE THREAD

**Issue by koolll** [SocialbitGmbH/SwiftAddressBook#41]
Hi I love your lib so much. But i got one question now. I doing an apps which allow to scan vcard qr and add to contact. I am able to scan the qr which getting string result. But How can I add the contact from that result? So did this lib is support this feature? if yes? Can you give me some example?

Thanks

**Comment by TAKeanice** [comment]
Fun fact: I have started this library exactly for extending an QR app with that feature (never implemented it, though). There are two methods for converting to and from vCard strings in SwiftAddressBookPerson:
 `createInSourceWithVCard(source : SwiftAddressBookSource, vCard : String) -> [SwiftAddressBookPerson]?` and for the inverse: `createVCard(people : [SwiftAddressBookPerson]) -> String`. I would love if you could integrate a demonstration into the sample app as well (and possibly also into the tests?). If something is broken there, feel free to submit another issue!

**Comment by koolll** [comment]
Hi thanks will attach the example code. Btw i am new for  . What doest the SwiftAddressBookSource  i need to put?
swiftcreateInSourceWithVCard(source : SwiftAddressBookSource, vCard : String)

**Comment by TAKeanice** [comment]
The iOS Address Book is an accumulation of several sources of address data. It can be CardDAV or iCloud or the local address book for example. You can retrieve the default source through the member variable `defaultSource` of the `SwiftAddressBook` class.

**Comment by koolll** [comment]
Hi Sorry for bothering you.
I try using below code. i not getting error . But not contact is created. any solution?

   var result = "MECARD:N:koo;;"
        var person = SwiftAddressBookPerson.create()
        swiftAddressBook?.requestAccessWithCompletion({ (success, error) -> Void in
            if success {
               var source = swiftAddressBook?.defaultSource?.convertToSource()
                
                    SwiftAddressBookPerson.createInSourceWithVCard(source!, vCard: result)

                
                
                //do something with swiftAddressBook
            }
            else {
                //no success. Optionally evaluate error
            }
        })

**Comment by TAKeanice** [comment]
It´s ok, I asked you for telling me your result ;)
There are several strange things in your solution, though.
First, the person does not need to be created like you do in line 2. Second, I´m not sure if `result` contains a valid VCard (don´t know where it comes from, either). Third, `createInSourceWithVCard` returns the person (inside an array), but you are not taking any reference to it.
Please review those issues in your code, then try again.

**Comment by koolll** [comment]
Hi I use any generator to generate the vcard result. Btw i had change the result . Then i remove the create person . Please see the below code. Btw i check the let abPersons : NSArray? = ABPersonCreatePeopleInSourceWithVCardRepresentation(source.internalRecord, data).takeRetainedValue() is return me nil. DId i did something wrong?

 var result = "BEGIN:VCARD VERSION:2.1 N:chong;koo END:VCARD"
        swiftAddressBook?.requestAccessWithCompletion({ (success, error) -> Void in
            if success {
               var source = swiftAddressBook?.defaultSource?.convertToSource()
                
                SwiftAddressBookPerson.createInSourceWithVCard(source!, vCard: result)
                
                //do something with swiftAddressBook
            }
            else {
                //no success. Optionally evaluate error
            }
        })

**Comment by TAKeanice** [comment]
The response may be nil in case no person was found in your VCard, the VCard is invalid, or the source is invalid or nil. You don´t need to `convertToSource()` because `defaultSource` already is of type source.

**Comment by koolll** [comment]
Hi thanks for you patient :)
i change the vcard to var result = "BEGIN:VCARD\n VERSION:2.1\n N:chong;koo\n END:VCARD"
Now i am successfully to get the person( in array) . 

but i check my contact. the person still not added. did i need to add anything?

**Comment by TAKeanice** [comment]
Yes. You are just creating the person. You need to add it to the address book, then save the address book. After that, your contact should appear in the contacts app on your phone.
You should still be able to manipulate or display the person before saving the address book, though.

**Comment by koolll** [comment]
Hi I change my code at below. But getting two error  . Did i miss anything?
1) '_??' is not convertible to 'SwiftAddressBookRecord'
 2) '<<error type>>?' is not convertible to 'SwiftAddressBookRecord'

var source = swiftAddressBook?.defaultSource
                
                var item = SwiftAddressBookPerson.createInSourceWithVCard(source!, vCard: result)
                
                
                swiftAddressBook?.addRecord(item)
                swiftAddressBook?.save()

**Comment by koolll** [comment]
THanks alot!!! it working now.

**Comment by KhaledAld** [comment]
@koolll  how to export contact as vcard ???

**Comment by TAKeanice** [comment]
There is a corresponding function in SwiftAddressBookPerson.
