### ISSUE TITLE
How to get person abid (AddressBook Record Id)?

### ISSUE THREAD

**Issue by anurmatov** [SocialbitGmbH/SwiftAddressBook#42]

**Comment by TAKeanice** [comment]
There was one fork implementing this, but no pull request so far. I´ll integrate that soon.
Just out of curiosity, what do you need the Record Id for?

**Comment by anurmatov** [comment]
Thanks for the quick response.
I want to integrate Whatsapp sending personal message (http://www.whatsapp.com/faq/en/iphone/23559013), and for doing this I need to know abid.

**Comment by TAKeanice** [comment]
Have a look at 
https://github.com/eito/SwiftAddressBook/commit/d39f798b27aba966371d9e6b95f9a91c430130e4
for a quick start.

**Comment by anurmatov** [comment]
Thanks, I will try later.

**Comment by anurmatov** [comment]
Tassilo, thanks. It works.
