### ISSUE TITLE
Contact with no Image

### ISSUE THREAD

**Issue by ed-mejia** [SocialbitGmbH/SwiftAddressBook#43]
Hi, First the first, Awesome work thanks for this library

I got an issue when testing on simulator and tried to get a contact image, returning in a crash .. I located the problem here (SwiftAddressBookPerson.swift) :

	public var image : UIImage? {
		get {
			return UIImage(data: ABPersonCopyImageData(internalRecord).takeRetainedValue())
		}
	}

If a user does not have picture the crash comes in, I updated to this, not sure if it is the best way.

    public var image : UIImage? {
        get {
            if ABPersonHasImageData(internalRecord) {
                return UIImage(data: ABPersonCopyImageData(internalRecord).takeRetainedValue())
            } else {
                return nil
            }
        }
    }

**Comment by TAKeanice** [comment]
Actually, I should be able to initialize `UIImage` with nil, for my taste... There are failable initializers in Swift, so why not? But you´re right, the documentation tells that it must be `nonnull`. Your way looks perfect to me, you could do it in one line by using the `?` operator like  `return ABPersonHasImageData(internalRecord) ? UIImage(data: ABPersonCopyImageData(internalRecord).takeRetainedValue()) : nil`, if that line would not get longer than the others. I´d love to have a pull request from you (please don´t forget to sign the contributors agreement first)

**Comment by adheus** [comment]
Same problem here. Hope this get fixed soon. Until there, manual fix for me. Thanks for the library and @ed-mejia thanks for the fix. :)

**Comment by TAKeanice** [comment]
I thought you would maybe send a pull request but if not, I will fix it myself this weekend.

**Comment by ed-mejia** [comment]
I'm Very sorry I will do it this weekend, I been short of time :(

**Comment by TAKeanice** [comment]
Me, too :) No need to be sorry!
