### ISSUE TITLE
Get office number , phone number and etc

### ISSUE THREAD

**Issue by koolll** [SocialbitGmbH/SwiftAddressBook#44]
Hi Is it possible to get the office number, fax number and phone number ? I am able to getting the person contact from vcard . But i not sure how to get the office number , fax number and etc. Please see my code below

 println(person!.phoneNumbers?.map( {$0.value} ))

Thanks

**Comment by TAKeanice** [comment]
This approach seems valid. What's wrong with it? If you want the default labels, ABAddressBook has constants for that. If you want to filter the values to get one specific label, use the filter function.

**Comment by koolll** [comment]
hi thanks, I am able to get the phone number. But i got another question. How can i get the postcode, state , stress1 and etc from the ABAddressBook?

**Comment by TAKeanice** [comment]
There are variables for all those things - just have a look at SwiftAddressBookPerson.

**Comment by koolll** [comment]
i try using below code to extract the street . but it get bad access :(

                               var first: AnyObject? = ABRecordCopyValue(person?.internalRecord, kABPersonAddressProperty)?.takeRetainedValue()
                                
                                
                                if let dict : NSDictionary = ABMultiValueCopyValueAtIndex(first, 0).takeUnretainedValue() as? NSDictionary
                                {
                                    let street = String(stringInterpolationSegment: dict.objectForKey(kABPersonAddressStreetKey))
                                    println(street)

                                }

**Comment by TAKeanice** [comment]
I'm not sure what you are doing there. That's not how to use SwiftAddressBook. It is there to avoid the stuff that you are doing in your code sample. Have another look: There already _is_ a variable for the address of a person.
