### ISSUE TITLE
Duplicated contacts

### ISSUE THREAD

**Issue by FezHacker** [SocialbitGmbH/SwiftAddressBook#45]
If a contact has a LINKED CONTACT, it duplicates when you call the person for allpeople!!

Is there a way to fix this?

**Comment by TAKeanice** [comment]
Actually, there is an API to determine the linked people of a person in class ‘SwiftAddressBookPerson‘: ‘allLinkedPeople‘.

**Comment by TAKeanice** [comment]
You can filter the list of all people using this information. If you want to show people like in the original address book, you would then need to combine the contacts that are linked

**Comment by zdesiree** [comment]
Do you have an example code how to do this? I'm also struggling with duplicate contacts because they have linked contacts.

**Comment by TAKeanice** [comment]
Just compare the linked contact's id with the contact ids in all people, and do not display the contact with equal id or throw it out of the array of contacts

**Comment by zdesiree** [comment]
Thanks for the implementation, unfortunately the method allPeopleExcludingLinkedContacts is taking very long. Maybe there's a way to make it more performant?

**Comment by FezHacker** [comment]
I actually already figured it out!
-- I found a small script online that fixed it!

**Comment by TAKeanice** [comment]
Yes, I have not optimized at all. I had no time for this. Can you link the code you found here, so I can have a look at it?
