### ISSUE TITLE
allPeople = nil

### ISSUE THREAD

**Issue by Yuop** [SocialbitGmbH/SwiftAddressBook#46]
if let people = swiftAddressBook?.allPeople {
Produce nil and doesn't show contacts in table view
Why? Access allowed 
ps Swift 2.0, Xcode 7 beta

**Comment by TAKeanice** [comment]
Swift 2.0 is not tested yet. iOS 9 has a new contacts API

**Comment by Yuop** [comment]
Even if I am developing for 8.x?

**Comment by TAKeanice** [comment]
Yes, it is each individually, iOS 9 AND Swift2.0 that have to be tested. Another issue could be some mistake in your code. Did you auto-transform the code to Swift2.0? The automatic transformation to Swift1.2 was rather bad.

**Comment by TAKeanice** [comment]
I have opened a new task to cover that and other issues that may arise from the upgrade: https://github.com/SocialbitGmbH/SwiftAddressBook/issues/47

**Comment by jmatheson** [comment]
I am experiencing the same nil result since upgrading to xcode 7 yesterday.

This function in SwiftAddressBookHelperMethods.swift is failing at the let of
 records as? [ABRecord]
and thus returns an empty set

func convertRecordsToPersons(records : CFArray?) -> [SwiftAddressBookPerson]? {
	let swiftRecords = (records as? [ABRecord])?.map {
        (record : ABRecord) -> SwiftAddressBookPerson in
		return SwiftAddressBookRecord(record: record).convertToPerson()!
	}
	return swiftRecords
}

**Comment by jmatheson** [comment]
hey @Yuop ... here is the fix. change records to records!
SwiftAddressBookHelperMethods.swift line 49

func convertRecordsToPersons(records : CFArray?) -> [SwiftAddressBookPerson]? {
let swiftRecords = (records! as? [ABRecord])?.map {
(record : ABRecord) -> SwiftAddressBookPerson in
return SwiftAddressBookRecord(record: record).convertToPerson()!
}
return swiftRecords
}

**Comment by jmatheson** [comment]
I also had to make a change to Label for Phone numbers by updating the following function in SwiftAddressBookPerson.swift

	private func extractMultivalueProperty<T>(propertyName : ABPropertyID) -> Array<MultivalueEntry<T>>? {
		var array = Array<MultivalueEntry<T>>()
		let multivalue : ABMultiValue? = extractProperty(propertyName)
		for i : Int in 0..<(ABMultiValueGetCount(multivalue)) {
			let value : T? = ABMultiValueCopyValueAtIndex(multivalue, i).takeRetainedValue() as? T
			if let v : T = value {
				let id : Int = Int(ABMultiValueGetIdentifierAtIndex(multivalue, i))
                
                var label = ""
                if let val = ABMultiValueCopyLabelAtIndex(multivalue, i) {
                    label = val.takeRetainedValue() as String
                }
                
                array.append(MultivalueEntry(value: v, label: label, id: id))
			}
		}
		if array.count > 0 {
			return array
		}
		else {
			return nil
		}
	}

**Comment by TAKeanice** [comment]
The first is no proper fix. It will simply crash upon passing nil!
What have you changed in the second fix? If it's about labels: They are optional, thus can contain nil. Not necessary to assign an empty string.

**Comment by jmatheson** [comment]
Feel free to use how you see fit, but these were the two areas that need some work in to get it working. May not be a proper fix; thus no pull request.
