### ISSUE TITLE
Prepare for iOS9 and Swift2.0

### ISSUE THREAD

**Issue by TAKeanice** [SocialbitGmbH/SwiftAddressBook#47]
iOS 9 has a new contact interface. Maybe the new `@available` has to be used for a complete overhaul, so that existing apps can use the SwiftAddressBook with both, the old and the new model. If possible at all.

**Comment by aliHafizji** [comment]
@TAKeanice Is this something you're working on? I moved my project to use xcode 7 today and this is the only library that needs to be updated.

**Comment by TAKeanice** [comment]
Yes, I am working on this. The tests are not running yet, but there is a promising pull request.

**Comment by TAKeanice** [comment]
Merged swift_2.0 Branch: https://github.com/SocialbitGmbH/SwiftAddressBook/pull/65
With this, the wrapper is now completely compatible with [Swift2.0](https://developer.apple.com/swift/blog/?id=29) (*not* backwards compatible), and [iOS9](https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html) (*backwards compatible* until iOS7, if you manually copy the files), and [Xcode7](https://developer.apple.com/library/prerelease/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_7_0.html) (*not* backwards compatible). Just install like you are used to with pod update or pod install, version [0.5.0](https://cocoapods.org/pods/SwiftAddressBook)!
