### ISSUE TITLE
CocoaPods 0.36.0.beta.2 support

### ISSUE THREAD

**Issue by albertbori** [SocialbitGmbH/SwiftAddressBook#5]
CocoaPods has functioning [support for Swift frameworks](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) now. It'd be great if this library used it. I'd submit a pull request with the changes, but I think @TAKeanice should probably head that up, since it would be highly disruptive to un-merged pull-requests/branches.

If you do decide support CocoaPods, I recommend splitting out all the classes from `SwiftAddressBookWrapper.swift` into their own files when you do this, to make future development easier.

**Comment by TAKeanice** [comment]
I have already implemented that locally, but it dues not yet work properly. I can make a branch for that, too, and upload the pod as implemented so far.

**Comment by TAKeanice** [comment]
Problem with splitting up is about some private methods used across classes. Either I duplicate those methods or leave those classes in one file

**Comment by TAKeanice** [comment]
Additionally, dynamic frameworks are only supported since iOS 8, thus, to maintain compatibility with iOS 7, people have to copy the file into the project anyway

**Comment by albertbori** [comment]
Yea, they'd have to be evaluated in a case by case scenario. Some of them could probably be refactored into base class scenarios, or at worst, made internal.

Go ahead and push your CocoaPods branch, and I'll take a look at it.

**Comment by TAKeanice** [comment]
Cocoapods Branch is up (and not running yet ;) )
