### ISSUE TITLE
Sometimes extractProperty crashes

### ISSUE THREAD

**Issue by zdesiree** [SocialbitGmbH/SwiftAddressBook#55]
Having the same people in the address book, only sometimes the app crashes at the following line:
<img width="925" alt="bildschirmfoto 2015-08-22 um 10 29 33" src="https://cloud.githubusercontent.com/assets/2411336/9423266/b45065f8-48bd-11e5-8ccf-229a3d8c989b.png">

**Comment by TAKeanice** [comment]
Do you take care about accessing the AddressBook from the same thread always?

**Comment by zdesiree** [comment]
Actually I don't take care of this. I will check this thanks for the hint.

**Comment by TAKeanice** [comment]
Can you update me on the status of this issue please?
Eventually, I want to make SwiftAddressBook threadsafe. There was another issue about that already: https://github.com/SocialbitGmbH/SwiftAddressBook/issues/37
It would be cool if you could do this for the public, if you are doing it for your copy anyway (in the long run, not making SwiftAddressBook _itself_ thread safe does not sound very viable to me)!

**Comment by zdesiree** [comment]
I'm getting all people on a background thread so I think threads could really cause the issue here. But I have no experience with threadsafe classes so unfortunately I can't help.

**Comment by TAKeanice** [comment]
Any more issues? I will close this issue, if you want to add any information please comment and reopen.
