### ISSUE TITLE
Test are failing

### ISSUE THREAD

**Issue by kostiakoval** [SocialbitGmbH/SwiftAddressBook#57]
Clone the repo. Run the test see errors. I have empty agrees book on my emulator and test are failing

**Comment by TAKeanice** [comment]
Have you allowed access to the address book before? There is a script contained in the repository, it gives SwiftAddressBook access to the address book of all simulators. Try running this and tell me if it is working afterwards.
If not, I need more information, like your build environment (IDE version, simulator used, OS version, etc.)
