### ISSUE TITLE
Crash when SwiftAddressBookPerson.organization is set to nil

### ISSUE THREAD

**Issue by albertbori** [SocialbitGmbH/SwiftAddressBook#6]
Using Xcode 6.1, the following line causes the app to crash, if the value passed in is nil:

    person.organization = nil

Log:

	<unknown>:0: error: -[AutomationTests.MyTests beforeAll] : failed: caught "NSInvalidArgumentException", "*** -[NSPlaceholderString initWithString:]: nil argument"
	(
		0   CoreFoundation                      0x0000000109bd2f35 __exceptionPreprocess + 165
		1   libobjc.A.dylib                     0x0000000109787bb7 objc_exception_throw + 45
		2   CoreFoundation                      0x0000000109bd2e6d +[NSException raise:format:] + 205
		3   Foundation                          0x0000000109348063 -[NSPlaceholderString initWithString:] + 102
		4   MyApp                            	0x0000000108b91324 _TTDFE8MyAppCSo8NSStringcfMS0_FT6stringGSqSS__GSqS0__ + 660
		5   MyApp                            	0x0000000108b816bb _TFE8MyAppCSo8NSStringCfMS0_FT6stringGSqSS__GSqS0__ + 139
		6   MyApp                            	0x0000000108b82bf0 _TFC8MyApp22SwiftAddressBookPersons12organizationGSqCSo8NSString_ + 560
		7   AutomationTests                     0x0000000117e9c214 _TFC15AutomationTests8MyTests9beforeAllfS0_FT_T_ + 3268
		8   CoreFoundation                      0x0000000109acac8c __invoking___ + 140
		9   CoreFoundation                      0x0000000109acaae2 -[NSInvocation invoke] + 290
		10  XCTest                              0x0000000117f750f7 -[XCTestCase invokeTest] + 253
		11  XCTest                              0x0000000117f752f8 -[XCTestCase performTest:] + 150
		12  KIF                                 0x0000000117fb7866 +[KIFTestCase performSetupTearDownWithSelector:] + 85
		13  XCTest                              0x0000000117f73f65 -[XCTestSuite performTest:] + 229
		14  XCTest                              0x0000000117f7ebf5 -[XCTest run] + 260
		15  XCTest                              0x0000000117f73ffb -[XCTestSuite performTest:] + 379
		16  XCTest                              0x0000000117f7ebf5 -[XCTest run] + 260
		17  XCTest                              0x0000000117f73ffb -[XCTestSuite performTest:] + 379
		18  XCTest                              0x0000000117f7ebf5 -[XCTest run] + 260
		19  XCTest                              0x0000000117f710bc __25-[XCTestDriver _runSuite]_block_invoke + 56
		20  XCTest                              0x0000000117f7bead -[XCTestObservationCenter _observeTestExecutionForBlock:] + 162
		21  XCTest                              0x0000000117f70ff0 -[XCTestDriver _runSuite] + 269
		22  XCTest                              0x0000000117f71a1d -[XCTestDriver _checkForTestManager] + 234
		23  XCTest                              0x0000000117f81af0 +[XCTestProbe runTests:] + 182
		24  Foundation                          0x0000000109340d55 __NSFireDelayedPerform + 387
		25  CoreFoundation                      0x0000000109b3af64 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
		26  CoreFoundation                      0x0000000109b3ab25 __CFRunLoopDoTimer + 1045
		27  CoreFoundation                      0x0000000109afde5d __CFRunLoopRun + 1901
		28  CoreFoundation                      0x0000000109afd486 CFRunLoopRunSpecific + 470
		29  GraphicsServices                    0x000000010c8fd9f0 GSEventRunModal + 161
		30  UIKit                               0x000000010a202420 UIApplicationMain + 1282
		31  MyApp                            	0x0000000108c34aee top_level_code + 78
		32  MyApp                            	0x0000000108c34b2a main + 42
		33  libdyld.dylib                       0x00000001102df145 start + 1
		34  ???                                 0x000000000000000a 0x0 + 10
	)

**Comment by TAKeanice** [comment]
Problem is the compiler confuses the convenience initializer with the standard initializer NSString(string: ) because overloading with optional type does not seem to be possible. Please test my fix and confirm whether it works

**Comment by albertbori** [comment]
This fix worked. Thanks!
