### ISSUE TITLE
swiftAddressBook?.allPeople is raising exec bad access.

### ISSUE THREAD

**Issue by najmul-hasan-csebuet** [SocialbitGmbH/SwiftAddressBook#60]
This is occurring not frequently.

**Comment by TAKeanice** [comment]
Please read https://github.com/SocialbitGmbH/SwiftAddressBook/issues/55
And also check the linked issues. If the problem can't be solved in any way described there, we can reopen this issue.

**Comment by najmul-hasan-csebuet** [comment]
Checking. Thanks for your response.
