### ISSUE TITLE
Calling SwiftAddressBook.personWithRecordId with a non-existing record id crashes

### ISSUE THREAD

**Issue by dbenninger** [SocialbitGmbH/SwiftAddressBook#61]
ABAddressBookGetPersonWithRecordID returns NULL if the record does not exist. Could you please add a null check?

e.g.:
public func personWithRecordId(recordId : Int32) -> SwiftAddressBookPerson? {
if let record = ABAddressBookGetPersonWithRecordID(internalAddressBook, recordId) {
       return SwiftAddressBookRecord.from(record.takeUnretainedValue()) as? SwiftAddressBookPerson
}
return nil
}

**Comment by TAKeanice** [comment]
The from function needs to be able to take null, then a simple question mark before `takeUnretainedValue` should be enough.

**Comment by dbenninger** [comment]
Sure, whatever works...
