### ISSUE TITLE
CompositeName is nil

### ISSUE THREAD

**Issue by Cordt** [SocialbitGmbH/SwiftAddressBook#66]
The compositeName property of a Person record is always nil, albeit first and lastName are set.

**Comment by TAKeanice** [comment]
Newest Swift2 version of this pod? Which OS?

**Comment by Cordt** [comment]
I used this pod:
pod 'SwiftAddressBook', :git => 'https://github.com/SocialbitGmbH/SwiftAddressBook.git', :branch => 'swift_2.0'
For iOS 8+ with XCode 7, Swift 2.0

**Comment by TAKeanice** [comment]
The branch is actually not necessary any more, version https://github.com/SocialbitGmbH/SwiftAddressBook/releases/tag/0.5.0 is fully Swift 2.0. I tackled a few problems before merging, so make sure (by using the master branch) that all changes are included!

**Comment by Cordt** [comment]
I switched back to master
pod 'SwiftAddressBook', :git => 'https://github.com/SocialbitGmbH/SwiftAddressBook.git', :branch => 'master'
and can confirm that compositeName is nil for all persons on both the simulator and a device.

**Comment by TAKeanice** [comment]
Thank you! I will investigate in this. Concerning the branch: Jou can make it even simpler: Just use `pod SwiftAddressBook` ;)
