### ISSUE TITLE
Images Save are rotated.

### ISSUE THREAD

**Issue by thedangler** [SocialbitGmbH/SwiftAddressBook#67]
when I save the image for a profile its always rotated counter clockwise 90 deg.
The image that I save to the camera roll is fine, as well as the image I use to preview.

**Comment by TAKeanice** [comment]
Obviously, the image has to be "physically" rotated before saving. UIImages contain a metadata entry for the rotation, the actual orientation is always the same. I will look into that.

**Comment by thedangler** [comment]
Thank you, I am setting the orientation. I hope this helps.
image = UIImage(CGImage: cgImageRef!, scale: 1.0, orientation: UIImageOrientation.Right)
//image is fine
self.savePersonToContacts(self.ContactInfoView.NameInputText!,number: self.ContactInfoView.NumberInputText!,image:image)
//SwiftAddressBook
if(image != nil){
                person.setImage(image!)  // image gets wonky
}

Maybe i have to re orient it?

**Comment by TAKeanice** [comment]
Please see the added test case and modify it so that it fails like your example
