### ISSUE TITLE
cannot install via pod

### ISSUE THREAD

**Issue by vinbhai4u** [SocialbitGmbH/SwiftAddressBook#69]
getting an error

[!] Unable to find a specification for `SwiftAddressBook`

**Comment by TAKeanice** [comment]
Can you post your podfile and the complete output of pod install please? Have no time to check myself right now, but maybe I can see the error there already.

**Comment by vinbhai4u** [comment]
pod file:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod "SwiftAddressBook"
pod 'RandomKit', '~> 1.5.0'

error from terminal

Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `SwiftAddressBook`

**Comment by TAKeanice** [comment]
Ok. What I read from that statement is, that the SwiftAddressBook specification was not found in the repository which you gave as "source". Can you omit that parameter and try again? Because there obviously is an entry in the CocoaPods library: https://cocoapods.org/pods/SwiftAddressBook

Otherwise, just try referencing this repo directly in your podfile.

Please inform me about your results!

**Comment by TAKeanice** [comment]
Even in your source repository, there are specifications for SwiftAddressBook... Weird that it doesn't find them!
https://github.com/CocoaPods/Specs/search?utf8=✓&q=SwiftAddressBook&type=Code

**Comment by vinbhai4u** [comment]
How can I do that?

what should I give in pod file?

**Comment by TAKeanice** [comment]
Have a look at https://github.com/SocialbitGmbH/SwiftAddressBook/blob/master/Example/Podfile
Just leave away the :path parameter.

**Comment by TAKeanice** [comment]
@vinbhai4u did it work?

**Comment by vinbhai4u** [comment]
sorry was busy will check tomorrow and let you know.

On Thu, Nov 12, 2015 at 8:25 PM, Tassilo Karge <notifications@github.com>
wrote:

> @vinbhai4u <https://github.com/vinbhai4u> did it work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SocialbitGmbH/SwiftAddressBook/issues/69#issuecomment-156127770>
> .
>



-- 
Regards
Vineeth Vijayan

**Comment by TAKeanice** [comment]
Updates?
