### ISSUE TITLE
Fix SwiftAddressBook for Swift 1.2

### ISSUE THREAD

**Issue by TAKeanice** [SocialbitGmbH/SwiftAddressBook#7]
I have branched SwiftAddressBook today and applied some fixes for Swift 1.2, but still not able to compile with the first XCode Beta (right now it´s an segmentation fault by the compiler, maybe eventually that will go away when apple releases the second beta, but maybe it´s in the code, too). I would appreciate any suggestion or pull request regarding this topic. Thank you for contributing!

**Comment by elprl** [comment]
I mentioned how I fixed those segmentation faults in issue #4 . Comment out the singleton code and go from there.

**Comment by TAKeanice** [comment]
Thanks for the advice. However, I´ll first try to compile without optimization, and if that works, I do not really want to change the code, because the problem is on Apples side and Swift 1.2 is still in the beta phase. Maybe it will get fixed later on, then porting the code to the Swift 1.2 version of SwiftAddressBook is much easier

**Comment by elprl** [comment]
Looks like a lot of people (including myself) experience the segmentation fault issue when you use a class name as a variable (even if in lowercase). Try changing `var swiftAddressBook` to `var swiftAddressBk` and see if that fixes it.

**Comment by badescuga9** [comment]
from my experience with segmentation errors in swift, their fix rate is very low. as a side note, i've changed the swiftAddressBook to swiftAddressBk with no success.

**Comment by TAKeanice** [comment]
Thanks for ruling out some of the possibilities. I´ve had no time so far for continuing to convert SwiftAddressBook for Swift 1.2 yet, due to the numerous issues with the current version. I will continue to do so soon. Possibly I´ll just re-convert the current master branch, because several changes were made which are not yet in the 1.2 branch

**Comment by dgdosen** [comment]
A couple of comments on using the 1.2 branch with the released version of Swift 1.2:

I notice an error on "MultiValue" properties - like addresses, social networks, etc - will crash whenever you have an empty property before you try to set it.   I didn't spend much time on the issue because the nested array/dictionary/tuple structure was a bit of a pain to deal with.

I'm unable to use a cast of a person (SwiftAddressBookPerson) to an address book record (ABRecordRef) for use in ABNewPersonViewController.displayedPerson

Do you still plan on taking a look at 1.2 now that it's finalized?

**Comment by TAKeanice** [comment]
Of course. I will have a really stressful time until monday, so I´m not sure when I can spare some minutes for that project. I´d recommend to use Swift 1.1 as long as Swift 1.2 version is not fixed. The Swift 1.2 branch does not contain a considerable amount of changes, since the beta versions I initially used were way too unstable. I will make a new branch from the current master and convert it to Swift 1.2 then

**Comment by TAKeanice** [comment]
@dgdosen  yes, that structure is a little painful to deal with, but have a look at the example for reference. This is still much easier to deal with than the blank ABAddressBook.
About your problem of  casting to ABRecordRef: you need to use the internalRecord property. Swift address book person is of course not an ABRecordRef, it only contains one.

**Comment by dgdosen** [comment]
Ah - thanks for the pointer on the internalRecord - I didn't see (or bother to look :)) at that inheritance chain... 

Thanks for the update - our scenario now works.
