### ISSUE TITLE
Composite Name is nil for Swift 2.1/iOS 9.2 on Xcode 7.2

### ISSUE THREAD

**Issue by daisyramos317** [SocialbitGmbH/SwiftAddressBook#70]
The integration is perfect besides that compositeName is returning nil. 
This is following the example provided in the repo.

**Comment by TAKeanice** [comment]
I will check this on Friday, consider it a Christmas gift :D Thank you for reporting!

**Comment by daisyramos317** [comment]
Many thanks! :+1:

**Comment by TAKeanice** [comment]
I was not able to reproduce your problem. If you have a look at the example app, there are two "TODO"s. If you comment the corresponding code blocks in and run the example, you should be able to see the table view filled with the composite name of all people in the address book.
I ran it on the iPhone 6 iOS9.2 simulator. If you don´t get the same result please comment again.

**Comment by salabaha** [comment]
It might work on simulator but not on the device. I'm using your library as well. And it was working perfectly on the simulator but didn't work for me on the device. I was forced to rewrite it a little bit to work on device.

**Comment by TAKeanice** [comment]
Can you share how you changed the code in order to make it work?

**Comment by salabaha** [comment]
Would love to make a pull request but because of  lack of time I'm sharing my changes as archive attached here. Most of the changes I have made are in  SwiftAddressBookPerson and SwiftAddressBookWrapper classes. Let me know if you need anything more from me.
[SwiftAddressBook.zip](https://github.com/SocialbitGmbH/SwiftAddressBook/files/66613/SwiftAddressBook.zip)

**Comment by TAKeanice** [comment]
@salabaha I really like your changes, you have sanitized many compromises that I had to make in the old swift versions. Also really cool that you have finally implemented the observing functionality! I would like to take your changes completely.  There are a few things I did not understand from looking over them quickly: What is the purpose of the AddressBook as a member variable of SwiftAddressBookRecord, and why did you decide against using the `from` function from SwiftAddressBookRecord in SwiftAddressBookWrapper to convert a record to some specialized record, in favor of the initializer?

**Comment by TAKeanice** [comment]
But they still did not change the compositeName problem for me, which I also encountered on the device now...

**Comment by TAKeanice** [comment]
However, it was only the broken optional unwrapping again (I have no idea what is going wrong there in Swift...). First casting to NSString and then to String succeeds!

**Comment by daisyramos317** [comment]
@TAKeanice The corresponding code blocks "TODO"s are commented,  compositeName is still nil on device running iOS 9.2. It works fine on iOS 8.4. It seems to be a type casting issue you mentioned above.

**Comment by TAKeanice** [comment]
Yes, definitely. I have fixed that in the last commit. Pod update incoming.

**Comment by TAKeanice** [comment]
@salabaha your changes don´t pass the tests yet, but I will come back to them. If you could comment on the questions above in a separate task it would be really helpful :)

**Comment by TAKeanice** [comment]
Ok, pod is pushed. We are at version version [0.5.1](https://github.com/SocialbitGmbH/SwiftAddressBook/releases/tag/0.5.1) now! `pod update` should make your Christmas holiday better (and if you don´t celebrate it, at least your weekend) :)

**Comment by daisyramos317** [comment]
Thanks actually I tried pod update but it didn't recognize v 0.5.1 might take a while however I added the change manually and can confirm it works. Happy Holidays from the east coast!

**Comment by TAKeanice** [comment]
Nope, it took a while for me to realize that the push had not worked... Should be up now. Frohe Weihnachten from Germany ;)
