### ISSUE TITLE
Continue discussing merge started in issue #70

### ISSUE THREAD

**Issue by salabaha** [SocialbitGmbH/SwiftAddressBook#71]

**Comment by salabaha** [comment]
So this is the archive with the code we would like to merge. 
[SwiftAddressBook.zip](https://github.com/SocialbitGmbH/SwiftAddressBook/files/67241/SwiftAddressBook.zip)

**Comment by salabaha** [comment]
Answers to the questions asked in issue #70: 
1. addressBook property in SwiftAddressBookRecord is redundant. Need to remove it. 
2. I needed to use init method instead of *from* function because in init method we are using ABAddressBookGetPersonWithRecordID function which force internalRecord to load all existing person data. (Fixed some person data loading bugs.)

**Comment by TAKeanice** [comment]
I will check this and come back if there are further questions. Thanks for your help :)

**Comment by salabaha** [comment]
I have made some code cleaning and refactoring. Plus rollback removed addressBook property in SwiftAddressBookRecord. We need to keep reference to addressBook in SwiftAddressBookRecord in order to be able to get person data like phone number from internalRecord.
[SwiftAddressBook.zip](https://github.com/SocialbitGmbH/SwiftAddressBook/files/70561/SwiftAddressBook.zip)

**Comment by TAKeanice** [comment]
I will do it in the first week of the new year (new year resolutions: more projects ☑️)
