### ISSUE TITLE
requestAccessWithCompletion error 0.6.1

### ISSUE THREAD

**Issue by buskerone** [SocialbitGmbH/SwiftAddressBook#73]
Anyone has this error with version 0.6.1 ? 
<img width="756" alt="captura de pantalla 2016-01-04 a las 12 16 01" src="https://cloud.githubusercontent.com/assets/2034112/12092736/a5a4ec10-b2dd-11e5-8747-ff1b030a80dd.png">

**Comment by TAKeanice** [comment]
Just change `swiftAddressBook?` to `SwiftAddressBook`. This is due to a slight interface change.

**Comment by TAKeanice** [comment]
To be precise: `requestAccessWithCompletion` has become a class method.
