### ISSUE TITLE
Getting ABRecordID

### ISSUE THREAD

**Issue by simonlinj** [SocialbitGmbH/SwiftAddressBook#74]
I need the ABRecordID to able to send/share messages to WhatsApp. I think `SwiftAddressBookPerson` should have a getter for ABRecordID

Currently Im getting it with:
```
let recordID : ABRecordID = ABRecordGetRecordID(contact.internalRecord)
```

**Comment by TAKeanice** [comment]
SwiftAddressBookPerson is a subclass of SwiftAddressBookRecord, which has the recordId property.

**Comment by simonlinj** [comment]
Ohh I was looking in the wrong place! Thanks!
