### ISSUE TITLE
iOS 9 update ?

### ISSUE THREAD

**Issue by AndreiBoariu** [SocialbitGmbH/SwiftAddressBook#79]
iOS 9 update ?
I have a lot of warnings on my app, which starts with deployment target for iOS 9.

Thanks for great job ;)

**Comment by TAKeanice** [comment]
The compatibility should be there, but I will look into it. Sorry for the late reply.

**Comment by TAKeanice** [comment]
If you meant iOS 9.3, there is a new version now that should fix all issues with it. Please check out the newest version and close if it fixes your issue. Thank you!
