### ISSUE TITLE
Missing samples in Readme

### ISSUE THREAD

**Issue by albertbori** [SocialbitGmbH/SwiftAddressBook#8]
The following code samples would be awesome to have in the readme:

- Adding a new contact
- Updating an existing contact (adding an email address & changing the name)
- Removing a contact

**Comment by TAKeanice** [comment]
There are some examples now in the "How to" section of the wiki. Please close if they seem sufficient to you, otherwise request some more :)

**Comment by albertbori** [comment]
Those look great! The only thing I would add is to show how to set values on a person. Specifically, the requirement of using an array of `MultivalueEntry` can be a bit unclear.

**Comment by TAKeanice** [comment]
Ok, I will comment on that in the sample
