### ISSUE TITLE
Method for extracting specific contacts

### ISSUE THREAD

**Issue by ZahidKsoft** [SocialbitGmbH/SwiftAddressBook#81]
Can we have a method by which we can extract some specific contacts from the address book based on like name, phone number etc as that will reduce the overhead of iterating through the contacts to find the desired one. Something similar to the .filter{}..

**Comment by TAKeanice** [comment]
There are the methods `personWithRecordId` and `personsWithName` in the main class. Other attributes are not accessible via the ABAddressBook methods, which most probably means that they do not have an index on them. Iterating through them is the only thing that is possible, and smart caching of the results.
