### ISSUE TITLE
How to preview

### ISSUE THREAD

**Issue by happiehappie** [SocialbitGmbH/SwiftAddressBook#82]
How to preview a contact before adding it.

I am currently implementing this in my qr scanner, it's supposed to preview before saving, but now my code just saves immediately. 

This is my code
let source = swiftAddressBook?.defaultSource
                        let person = SwiftAddressBookPerson.createInSourceWithVCard(source!, vCard: result.value)
                        swiftAddressBook?.addRecord(person![0])
                        swiftAddressBook?.save()

**Comment by TAKeanice** [comment]
Save, then preview using the AddressBookUI framework, and give the option to remove. The AddressBookUI does not allow to view unsaved records as far as I know.

**Comment by happiehappie** [comment]
How to do the preview part?

**Comment by TAKeanice** [comment]
Which part specifically? I think the question has already been answered.
