### ISSUE TITLE
Build error in Xcode 7.3

### ISSUE THREAD

**Issue by m-revetria** [SocialbitGmbH/SwiftAddressBook#85]
Hi, I just updated Xcode to version 7.3 and SwiftAddressBook stop building.

I'm getting two errors when trying to build version 0.6.1 in Xcode 7.3:

```
SwiftAddressBookWrapper.swift:105:7:` Closure cannot have keyword arguments

SwiftAddressBookWrapper.swift:118:10: Closure cannot have keyword arguments
```

Is master or any other branch currently working with Xcode 7.3?

**Comment by m-revetria** [comment]
Associated PR https://github.com/SocialbitGmbH/SwiftAddressBook/pull/84

**Comment by mitchellporter** [comment]
+1

**Comment by buffaloproject1** [comment]
+1

**Comment by buskerone** [comment]
+1

**Comment by gabrielcandiag** [comment]
+1

**Comment by TAKeanice** [comment]
yesyesyes :D Sorry for needing another day to find time to fix this issue. That issue will be definitely solved today. Cheers

**Comment by TAKeanice** [comment]
There is a new version now. Please check out the newest version and close if it fixes your issue. Thank you!

**Comment by mitchellporter** [comment]
Fixed it for me. Thanks @TAKeanice :)
