### ISSUE TITLE
Crash in using "swiftAddressBook?.allPeople"

### ISSUE THREAD

**Issue by najmul-csebuet** [SocialbitGmbH/SwiftAddressBook#87]
I am getting signal SIGABRT on:

    public var allPeople : [SwiftAddressBookPerson]? {
		return convertRecordsToPersons(ABAddressBookCopyArrayOfAllPeople(internalAddressBook).takeRetainedValue())
    }

Any suggestion for me pls?

**Comment by willwfsp** [comment]
Same with me

**Comment by TAKeanice** [comment]
Threading issues? That's the best guess I can make until I get more information. Please refer to the ABAddressBook documentation comments about threadsafety.

**Comment by najmul-csebuet** [comment]
Hi 
I printed is the call under main thread or not. It was from main thread.

**Comment by TAKeanice** [comment]
It's not about whether this one call is from the main thread, but what threads all the others are mapped to. Anyway, I can't give you a better guess until you provide more details regarding your crash.

**Comment by TAKeanice** [comment]
Since this is already quite old and there were no further responses, so I think it is not of interest any more

**Comment by ilkhomibodillayev** [comment]
I am getting crash:

fileprivate func convertNSDictionary<T : NSCopying, U, V, W>(_ d : NSDictionary?, keyConverter : (T) -> V, valueConverter : (U) -> W ) -> Dictionary<V, W>? {
		if let d2 = d {
			var dict = Dictionary<V,W>()
			for key in d2.allKeys as! Array<T> {
				let newKey = keyConverter(key)
				**let newValue = valueConverter(d2[key] as! U)**
				dict[newKey] = newValue
			}
			return dict
		}
		else {
			return nil
		}
	}

Any suggestion for me please?
