### ISSUE TITLE
Swift 2.3 or 3

### ISSUE THREAD

**Issue by EthanSchatzline** [SocialbitGmbH/SwiftAddressBook#91]
Will there be a new version to support Swift 2.3 or 3.0 soon?

**Comment by ctews** [comment]
Would also like to know if this will get in or if this project is still maintained at all? :)

**Comment by mkaya93** [comment]
@jochenklein will you update the library ?

**Comment by jochenklein** [comment]
@mkaya93, I'm the wrong guy for that. Maybe @TAKeanice?

**Comment by mkaya93** [comment]
@jochenklein thank you

**Comment by joshoconnor89** [comment]
Yes can you please update to Swift 3?  This is the only library in my project that is blocking my codebase from successfully converting to Swift 3.

**Comment by mrigo** [comment]
Same here for me like @joshoconnor89 , this is the only library in my project that is blocking my code :(
Thanks!

**Comment by TAKeanice** [comment]
Ok sorry for letting you wait and thank you for your patience. I am going to fix this within the next couple of days!

**Comment by TAKeanice** [comment]
If anybody has a suggestion... After spending several hours encountering non-explainable bugs (like bad access errors on perfectly compiled method invocations, like test code just does not execute in simulators of iOS <9.0) I pretty much gave up.
If you want a current status of my work, have a look at the branch https://github.com/SocialbitGmbH/SwiftAddressBook/tree/chunkyguy-swift3 and let me know if it works for you.

**Comment by joshoconnor89** [comment]
AddressBook is deprecated now.  I had to switch over to Contacts Framework.

**Comment by TAKeanice** [comment]
Well deprecated ususally doesn´t mean immediate removal. The Contacts Framework is a modern alternative provided by Apple which usually means more future-proofness, but of course it would be nice to be able to just continue using the same API as before, namely SwiftAddressBook for a number of apps. Unfortunately I have been slow updating and apparently I am not able to fix the problems arising in iOS10 in appropriate time.

**Comment by phoney** [comment]
I spent a little time looking at the chunkyguy-swift3 branch. The code looks correct to me. The place where I get crashes is in the errorIfNoSuccess method. If I pass nil for the CFError pointer parameter  it doesn't crash but the code looks like it should work. From the crashes I get I think there is a mismatch between the code in the swift3 headers for ABAddressBook and the actual code in the ABAddressBook library. 

I recommend several things to try to fix this problem:

1) Post an example to the apple forum to find out if there is a known solution or known problem.
2) File a bug with Apple. They will sometimes respond with workarounds or explanations if code is working as designed.
3) Use a DTS Incident to get code level support from Apple to solve this.

I think support from Apple is required to fix this issue.

**Comment by TAKeanice** [comment]
I am glad if Apple wanted to help, but I doubt it. They didn´t deprecate ABAddressBook without reason, it was a mess to fix the problems and work around the bugs, additionally it was not modern-style ObjectiveC or Swift code, but old CoreFoundation-style C code.

I consider that library deprecated. If anyone wants to continue working on compatibility with iOS 10, I am happy to merge any pull request!

**Comment by Sega-Zero** [comment]
@TAKeanice looked at your code, it's fine, but in a testcase that is crashing you should change a UIImage init code to:
```swift
guard let image = UIImage(named: "testImage") else { return }
```

the code `UIImage(named: "testImage", in: Bundle.init(for: type(of: self)), compatibleWith: nil)` returns nil because testImage does not exist in a test bundle. force unwrapping a nil value is a bad thing in any way.

the rest code looks fine on xcode 8.2, all tests are passing

**Comment by Sega-Zero** [comment]
@TAKeanice any chance to merge your branch to upstream?

**Comment by TAKeanice** [comment]
@Sega-Zero Thank you for the notice, I had already given up to be honest. Apparently the address book headers are exported to swift correctly again in the current Xcode version (8.2), in contrary to the old one that I tested with last (8.0 or 8.1). That makes the project useable again. I guess, after all the time the project hasn´t been working, there may not be much interest any more, but just in case, the master branch contains the current version now.
