### ISSUE TITLE
Crash while accessing allPeopleExcludingLinkedContacts

### ISSUE THREAD

**Issue by arunkputhenveedu** [SocialbitGmbH/SwiftAddressBook#93]
Hi SwiftAddressBook Team,

I wrote this in my app
`let phoneContacts: [SwiftAddressBookPerson]? = addressBook?.allPeopleExcludingLinkedContacts
`
Now in some cases(I am thinking of some **special linked contacts**) I am getting `Exception Codes: 0x000000008badf00d` exception and app crashes without launching after a few seconds, i.e. iOS watchdog is terminating the app due to its launch delay.

While tracing I found out **convertRecordsToPersons** is causing the problem.

```
func convertRecordsToPersons(records : CFArray?) -> [SwiftAddressBookPerson]? {
    let swiftRecords = (records as NSArray? as? [ABRecord])?.map {(record : ABRecord) -> SwiftAddressBookPerson in
        return SwiftAddressBookPerson(record: record)
    }
    return swiftRecords
}
```

Please help me to fix this problem.

**Comment by TAKeanice** [comment]
Well, the allPeopleExcludingLinkedContacts function is a very dirty hack in its current implementation. It may be that a bug in it causes convertRecordsToPersons to fail. To give you better advice I would need more information.
